# Generated by Django 5.2.6 on 2025-10-03 07:09

import vehicles.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la marque')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Marque de véhicule',
                'verbose_name_plural': 'Marques de véhicule',
                'db_table': 'vehicle_brands',
            },
        ),
        migrations.CreateModel(
            name='VehicleColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom de la couleur')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Couleur de véhicule',
                'verbose_name_plural': 'Couleurs de véhicule',
                'db_table': 'vehicle_colors',
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du type')),
                ('additional_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant additionnel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Type de véhicule',
                'verbose_name_plural': 'Types de véhicule',
                'db_table': 'vehicle_types',
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du modèle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='vehicles.vehiclebrand', verbose_name='Marque')),
            ],
            options={
                'verbose_name': 'Modèle de véhicule',
                'verbose_name_plural': 'Modèles de véhicule',
                'db_table': 'vehicle_models',
                'unique_together': {('brand', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du véhicule')),
                ('plaque_immatriculation', models.CharField(max_length=20, unique=True, verbose_name="Plaque d'immatriculation")),
                ('etat_vehicule', models.IntegerField(choices=[(1, '1 - Très mauvais état'), (2, '2 - Mauvais état'), (3, '3 - État passable'), (4, '4 - État correct'), (5, '5 - État moyen'), (6, '6 - Bon état'), (7, '7 - Très bon état'), (8, '8 - Excellent état'), (9, '9 - État quasi neuf'), (10, '10 - État neuf')], verbose_name='État du véhicule (1-10)')),
                ('photo_exterieur_1', models.ImageField(blank=True, null=True, upload_to=applications.vehicles.models.vehicle_image_upload_path, verbose_name='Photo extérieure 1')),
                ('photo_exterieur_2', models.ImageField(blank=True, null=True, upload_to=applications.vehicles.models.vehicle_image_upload_path, verbose_name='Photo extérieure 2')),
                ('photo_interieur_1', models.ImageField(blank=True, null=True, upload_to=applications.vehicles.models.vehicle_image_upload_path, verbose_name='Photo intérieure 1')),
                ('photo_interieur_2', models.ImageField(blank=True, null=True, upload_to=applications.vehicles.models.vehicle_image_upload_path, verbose_name='Photo intérieure 2')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=False, verbose_name='Actif')),
                ('is_online', models.BooleanField(default=False, verbose_name='En service')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='users.userdriver', verbose_name='Chauffeur')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehiclebrand', verbose_name='Marque')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehiclecolor', verbose_name='Couleur')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehiclemodel', verbose_name='Modèle')),
                ('vehicle_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicletype', verbose_name='Type de véhicule')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'db_table': 'vehicles',
                'ordering': ['-created_at'],
            },
        ),
    ]
