# Generated by Django 5.2.6 on 2025-10-03 06:10

import wallet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': '💰 Portefeuille',
                'verbose_name_plural': '💰 Portefeuilles',
                'db_table': 'wallets',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Solde après'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Complété le'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='error_message',
            field=models.TextField(blank=True, help_text="Message d'erreur en cas d'échec de la transaction", null=True, verbose_name="Message d'erreur"),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='freemopay_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Référence FreeMoPay'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Données supplémentaires en JSON', verbose_name='Métadonnées'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mobile_money', 'Mobile Money'), ('bank_transfer', 'Virement bancaire'), ('cash', 'Espèces'), ('other', 'Autre')], max_length=20, verbose_name='Méthode de paiement'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Numéro pour Mobile Money', max_length=15, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='reference',
            field=models.CharField(default=applications.wallet.models.generate_transaction_reference, help_text='Référence unique de la transaction', max_length=50, unique=True, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Complété'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Dépôt'), ('withdrawal', 'Retrait'), ('transfer_in', 'Transfert entrant'), ('transfer_out', 'Transfert sortant'), ('refund', 'Remboursement'), ('payment', 'Paiement')], max_length=20, verbose_name='Type de transaction'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
    ]
