# Generated by Django 5.2.4 on 2025-07-22 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='token',
            unique_together=set(),
        ),
    ]
