# Generated by Django 5.2.4 on 2025-07-22 07:34

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_token_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='ID Utilisateur')),
                ('user_type', models.CharField(choices=[('driver', 'Chauffeur'), ('customer', 'Client')], max_length=10, verbose_name="Type d'utilisateur")),
                ('document_name', models.CharField(max_length=100, verbose_name='Nom du document')),
                ('file', models.FileField(upload_to=api.models.document_upload_path, verbose_name='Fichier')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nom du fichier original')),
                ('file_size', models.IntegerField(verbose_name='Taille du fichier (bytes)')),
                ('content_type', models.CharField(max_length=100, verbose_name='Type de contenu')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'import")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
