# Generated by Django 5.2.4 on 2025-07-22 08:31

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=50, verbose_name='Marque')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du véhicule')),
                ('modele', models.CharField(max_length=50, verbose_name='Modèle')),
                ('couleur', models.CharField(max_length=30, verbose_name='Couleur')),
                ('plaque_immatriculation', models.CharField(max_length=20, unique=True, verbose_name="Plaque d'immatriculation")),
                ('etat_vehicule', models.IntegerField(choices=[(1, '1 - Très mauvais état'), (2, '2 - Mauvais état'), (3, '3 - État passable'), (4, '4 - État correct'), (5, '5 - État moyen'), (6, '6 - Bon état'), (7, '7 - Très bon état'), (8, '8 - Excellent état'), (9, '9 - État quasi neuf'), (10, '10 - État neuf')], verbose_name='État du véhicule (1-10)')),
                ('photo_exterieur_1', models.ImageField(blank=True, null=True, upload_to=api.models.vehicle_image_upload_path, verbose_name='Photo extérieure 1')),
                ('photo_exterieur_2', models.ImageField(blank=True, null=True, upload_to=api.models.vehicle_image_upload_path, verbose_name='Photo extérieure 2')),
                ('photo_interieur_1', models.ImageField(blank=True, null=True, upload_to=api.models.vehicle_image_upload_path, verbose_name='Photo intérieure 1')),
                ('photo_interieur_2', models.ImageField(blank=True, null=True, upload_to=api.models.vehicle_image_upload_path, verbose_name='Photo intérieure 2')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='api.userdriver', verbose_name='Chauffeur')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'db_table': 'vehicles',
                'ordering': ['-created_at'],
            },
        ),
    ]
