# Generated by Django 5.2.4 on 2025-07-22 10:05

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_vehicle'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_bonus_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant du parrainage')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Générale',
                'verbose_name_plural': 'Configurations',
            },
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('code', models.CharField(default=api.models.generate_referral_code, max_length=8, unique=True, verbose_name='Code de parrainage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'api'), ('model', 'userdriver')), models.Q(('app_label', 'api'), ('model', 'usercustomer')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Code de parrainage',
                'verbose_name_plural': 'Codes de parrainage',
                'db_table': 'referral_codes',
                'unique_together': {('user_type', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Solde')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'api'), ('model', 'userdriver')), models.Q(('app_label', 'api'), ('model', 'usercustomer')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Portefeuille',
                'verbose_name_plural': 'Portefeuilles',
                'db_table': 'wallets',
                'unique_together': {('user_type', 'user_id')},
            },
        ),
    ]
