# Generated by Django 5.2.4 on 2025-07-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_update_generalconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
    ]
