# Generated by Django 5.2.4 on 2025-07-22 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_generalconfig_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalconfig',
            options={'ordering': ['nom'], 'verbose_name': 'Configuration Générale', 'verbose_name_plural': 'Configurations Générales'},
        ),
    ]
