# Generated by Django 5.2.4 on 2025-07-22 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_load_default_configs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalconfig',
            options={'ordering': ['nom'], 'verbose_name': 'Configuration Générale', 'verbose_name_plural': 'Configurations'},
        ),
    ]
