# Generated by Django 5.2.4 on 2025-07-23 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_generalconfig_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la marque')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Marque de véhicule',
                'verbose_name_plural': 'Marques de véhicule',
                'db_table': 'vehicle_brands',
            },
        ),
        migrations.CreateModel(
            name='VehicleColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom de la couleur')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Couleur de véhicule',
                'verbose_name_plural': 'Couleurs de véhicule',
                'db_table': 'vehicle_colors',
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du type')),
                ('additional_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant additionnel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Type de véhicule',
                'verbose_name_plural': 'Types de véhicule',
                'db_table': 'vehicle_types',
            },
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='couleur',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='marque',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='modele',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vehiclebrand', verbose_name='Marque'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vehiclecolor', verbose_name='Couleur'),
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du modèle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='api.vehiclebrand', verbose_name='Marque')),
            ],
            options={
                'verbose_name': 'Modèle de véhicule',
                'verbose_name_plural': 'Modèles de véhicule',
                'db_table': 'vehicle_models',
                'unique_together': {('brand', 'name')},
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vehiclemodel', verbose_name='Modèle'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vehicletype', verbose_name='Type de véhicule'),
        ),
    ]
