# Generated by Django 5.2.4 on 2025-07-27 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_country_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la zone VIP')),
                ('prix_jour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de base jour (FCFA)')),
                ('prix_nuit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de base nuit (FCFA)')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': '👑 Zone VIP',
                'verbose_name_plural': '👑 Zones VIP',
                'db_table': 'vip_zones',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['country__name', 'name'], 'verbose_name': '🏙️ Ville', 'verbose_name_plural': '🏙️ Villes'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': '🌍 Pays', 'verbose_name_plural': '🌍 Pays'},
        ),
        migrations.CreateModel(
            name='VipZoneKilometerRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_kilometers', models.DecimalField(decimal_places=2, help_text="À partir de combien de km cette règle s'applique", max_digits=5, verbose_name='Kilométrage minimum')),
                ('prix_jour_per_km', models.DecimalField(decimal_places=2, help_text='Prix par kilomètre supplémentaire en journée', max_digits=10, verbose_name='Prix par km (jour)')),
                ('prix_nuit_per_km', models.DecimalField(decimal_places=2, help_text='Prix par kilomètre supplémentaire la nuit', max_digits=10, verbose_name='Prix par km (nuit)')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('vip_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kilometer_rules', to='api.vipzone', verbose_name='Zone VIP')),
            ],
            options={
                'verbose_name': '📏 Règle kilométrique VIP',
                'verbose_name_plural': '📏 Règles kilométriques VIP',
                'db_table': 'vip_zone_kilometer_rules',
                'ordering': ['vip_zone', 'min_kilometers'],
                'unique_together': {('vip_zone', 'min_kilometers')},
            },
        ),
    ]
