# Generated by Django 5.2.4 on 2025-07-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_vipzone_alter_city_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vipzonekilometerrule',
            options={'ordering': ['vip_zone', 'min_kilometers'], 'verbose_name': '📏 Règle KM', 'verbose_name_plural': '📏 Règles KM'},
        ),
        migrations.AddField(
            model_name='userdriver',
            name='is_partenaire_externe',
            field=models.BooleanField(default=False, verbose_name='Partenaire Externe'),
        ),
        migrations.AddField(
            model_name='userdriver',
            name='is_partenaire_interne',
            field=models.BooleanField(default=False, verbose_name='Partenaire Interne'),
        ),
    ]
