# Generated by Django 5.2.4 on 2025-08-08 18:55

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_vipzonekilometerrule_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_channel', models.CharField(choices=[('sms', 'SMS (Nexah)'), ('whatsapp', 'WhatsApp (Meta)')], default='sms', max_length=20, verbose_name='Canal de notification par défaut')),
                ('nexah_base_url', models.CharField(default='https://api.nexah.net/', max_length=255, verbose_name='URL de base Nexah')),
                ('nexah_send_endpoint', models.CharField(default='api/bulk/send', max_length=100, verbose_name="Endpoint d'envoi Nexah")),
                ('nexah_credits_endpoint', models.CharField(default='api/credits', max_length=100, verbose_name='Endpoint de crédits Nexah')),
                ('nexah_user', models.CharField(blank=True, max_length=100, verbose_name='Utilisateur Nexah')),
                ('nexah_password', models.CharField(blank=True, max_length=100, verbose_name='Mot de passe Nexah')),
                ('nexah_sender_id', models.CharField(default='WOILA', max_length=20, verbose_name='ID expéditeur Nexah')),
                ('whatsapp_api_token', models.TextField(blank=True, help_text="Token permanent pour l'API WhatsApp", verbose_name='Token API WhatsApp')),
                ('whatsapp_api_version', models.CharField(default='v18.0', help_text="Version de l'API Meta (ex: v18.0)", max_length=20, verbose_name="Version de l'API WhatsApp")),
                ('whatsapp_phone_number_id', models.CharField(blank=True, help_text='ID du numéro de téléphone WhatsApp (ex: xxxxxxxxxxxxxx)', max_length=100, verbose_name='ID du numéro WhatsApp')),
                ('whatsapp_template_name', models.CharField(default='woila_otp', max_length=100, verbose_name='Nom du template WhatsApp')),
                ('whatsapp_language', models.CharField(default='fr', max_length=10, verbose_name='Code langue du template WhatsApp')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Config Notifications',
                'verbose_name_plural': 'Config Notifications',
                'db_table': 'notification_configs',
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100, verbose_name='Identifiant (téléphone/email)')),
                ('otp', models.CharField(max_length=4, verbose_name='Code OTP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Vérifié')),
            ],
            options={
                'verbose_name': 'Vérification OTP',
                'verbose_name_plural': 'Vérifications OTP',
                'db_table': 'otps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='usercustomer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.profile_picture_upload_path, verbose_name='Photo de profil'),
        ),
        migrations.AddField(
            model_name='userdriver',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.profile_picture_upload_path, verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Actif'),
        ),
    ]
