# Generated by Django 5.2.4 on 2025-08-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_notificationconfig_otpverification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='En service'),
        ),
    ]
