# Generated by Django 5.2.4 on 2025-08-10 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_vehicle_is_online'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('notification_type', models.CharField(choices=[('welcome', 'Notification de bienvenue'), ('referral_used', 'Code parrain utilisé'), ('vehicle_approved', 'Véhicule approuvé'), ('system', 'Notification système'), ('order', 'Commande'), ('other', 'Autre')], default='system', max_length=20, verbose_name='Type de notification')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données supplémentaires (code parrain, ID véhicule, etc.)', verbose_name='Métadonnées')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu le')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('user_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'api'), ('model', 'userdriver')), models.Q(('app_label', 'api'), ('model', 'usercustomer')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_type', 'user_id', 'is_read'], name='notificatio_user_ty_10e4b9_idx'), models.Index(fields=['user_type', 'user_id', 'is_deleted'], name='notificatio_user_ty_4cda4f_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx'), models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx')],
            },
        ),
    ]
