# Generated by Django 5.2.4 on 2025-08-10 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_notification'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('token', models.TextField(unique=True, verbose_name='Token FCM')),
                ('platform', models.CharField(help_text='android, ios, web, etc.', max_length=20, verbose_name='Plateforme')),
                ('device_id', models.CharField(help_text="Identifiant unique de l'appareil", max_length=255, verbose_name="ID de l'appareil")),
                ('device_info', models.JSONField(blank=True, default=dict, help_text='Version OS, modèle, etc.', verbose_name='Informations appareil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='Dernière utilisation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('user_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'api'), ('model', 'userdriver')), models.Q(('app_label', 'api'), ('model', 'usercustomer')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Token FCM',
                'verbose_name_plural': 'Tokens FCM',
                'db_table': 'fcm_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_type', 'user_id'], name='fcm_tokens_user_ty_2508dd_idx'), models.Index(fields=['token'], name='fcm_tokens_token_25aa7b_idx'), models.Index(fields=['platform'], name='fcm_tokens_platfor_94d11f_idx'), models.Index(fields=['is_active'], name='fcm_tokens_is_acti_55e346_idx'), models.Index(fields=['last_used'], name='fcm_tokens_last_us_f2ea66_idx')],
                'unique_together': {('user_type', 'user_id', 'device_id')},
            },
        ),
    ]
