# Generated by Django 5.2.4 on 2025-08-14 18:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_usercustomer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustomer',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usercustomer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.profile_picture_upload_path, verbose_name='Photo de profil'),
        ),
        migrations.AddField(
            model_name='usercustomer',
            name='surname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdriver',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
