# Generated by Django 5.2.4 on 2025-08-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_usercustomer_name_usercustomer_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustomer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='usercustomer',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='usercustomer',
            name='surname',
        ),
    ]
