# Generated by Django 5.2.4 on 2025-09-11 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_usercustomer_name_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Référence unique de la transaction', max_length=50, unique=True, verbose_name='Référence')),
                ('user_id', models.PositiveIntegerField()),
                ('transaction_type', models.CharField(choices=[('deposit', 'Dépôt'), ('withdrawal', 'Retrait'), ('transfer_in', 'Transfert entrant'), ('transfer_out', 'Transfert sortant'), ('refund', 'Remboursement'), ('payment', 'Paiement')], max_length=20, verbose_name='Type de transaction')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Complété'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('payment_method', models.CharField(blank=True, choices=[('mobile_money', 'Mobile Money'), ('bank_transfer', 'Virement bancaire'), ('cash', 'Espèces'), ('other', 'Autre')], max_length=20, verbose_name='Méthode de paiement')),
                ('phone_number', models.CharField(blank=True, help_text='Numéro pour Mobile Money', max_length=15, verbose_name='Numéro de téléphone')),
                ('freemopay_reference', models.CharField(blank=True, max_length=100, verbose_name='Référence FreeMoPay')),
                ('freemopay_external_id', models.CharField(blank=True, max_length=100, verbose_name='ID externe FreeMoPay')),
                ('balance_before', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Solde avant')),
                ('balance_after', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Solde après')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données supplémentaires JSON', verbose_name='Métadonnées')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de completion')),
                ('user_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'api'), ('model', 'userdriver')), models.Q(('app_label', 'api'), ('model', 'usercustomer')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '💳 Transaction Wallet',
                'verbose_name_plural': '💳 Transactions Wallet',
                'db_table': 'wallet_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_type', 'user_id'], name='wallet_tran_user_ty_f8d9d7_idx'), models.Index(fields=['reference'], name='wallet_tran_referen_531c6d_idx'), models.Index(fields=['transaction_type'], name='wallet_tran_transac_377ecc_idx'), models.Index(fields=['status'], name='wallet_tran_status_c987ce_idx'), models.Index(fields=['created_at'], name='wallet_tran_created_33245a_idx'), models.Index(fields=['freemopay_reference'], name='wallet_tran_freemop_e5d9e4_idx')],
            },
        ),
    ]
