"""
Django settings for woila_backend project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0ync(lbk0o$byk)5+0%y9mzg(9=k#v9&1@qwh15n@wc_hc8(93'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'channels',
    'api',
    'order',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'woila_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'woila_backend.wsgi.application'
ASGI_APPLICATION = 'woila_backend.asgi.application'

# Channels configuration
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Spectacular settings for Swagger/Redoc
SPECTACULAR_SETTINGS = {
    'TITLE': 'Woilà Backend API',
    'DESCRIPTION': 'API pour l\'application VTC Woilà - MVP avec authentification chauffeurs et clients',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SORT_OPERATIONS': False,
}

# Jazzmin settings
JAZZMIN_SETTINGS = {
    "site_title": "🚗 Woilà Backend Admin",
    "site_header": "🚗 Woilà Backend Administration",
    "site_brand": "🚗 Woilà",
    "login_logo": None,
    "login_logo_dark": None,
    "site_logo_classes": "img-circle",
    "site_icon": "fas fa-car",
    "welcome_sign": "🎉 Bienvenue dans l'administration Woilà - Gérez votre plateforme VTC",
    "copyright": "© 2025 Woilà Backend - Plateforme VTC",
    "search_model": ["auth.User", "auth.Group", "api.UserDriver", "api.UserCustomer", "api.Vehicle"],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "🏠",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "📊", "url": "/admin/", "permissions": ["auth.view_user"]},
        {"name": "🆘", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
    ],
    "usermenu_links": [
        {"name": "👤 Mon profil", "model": "auth.user"},
        {"name": "🔧 Configurations", "url": "admin:api_generalconfig_changelist", "icon": "fas fa-cog"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["api", "auth"],
    "custom_links": {
        "api": [{
            "name": "📈 Tableau de bord",
            "url": "admin:index",
            "icon": "fas fa-chart-line",
            "permissions": ["api.view_generalconfig"]
        }]
    },
    "icons": {
        # Auth icons
        "auth": "fas fa-shield-alt",
        "auth.user": "fas fa-user-shield",
        "auth.Group": "fas fa-users-cog",
        
        # API App
        "api": "fas fa-mobile-alt",
        
        # Modèles avec emojis
        "api.UserDriver": "fas fa-user-tie",
        "api.UserCustomer": "fas fa-user-friends",
        "api.Token": "fas fa-key",
        "api.Document": "fas fa-file-alt",
        "api.Vehicle": "fas fa-car",
        "api.GeneralConfig": "fas fa-cogs",
        "api.Wallet": "fas fa-wallet",
        "api.ReferralCode": "fas fa-gift",
        
        # Vehicle related models
        "api.VehicleType": "fas fa-car-side",
        "api.VehicleBrand": "fas fa-industry",
        "api.VehicleModel": "fas fa-car-alt",
        "api.VehicleColor": "fas fa-palette",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible", 
        "auth.group": "vertical_tabs",
        "api.generalconfig": "horizontal_tabs",
        "api.vehicle": "horizontal_tabs",
    },
    # Thème et couleurs - Mode sombre par défaut
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary", 
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['file', 'console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'order': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# Personnalisation supplémentaire de l'interface Jazzmin - Thème sombre orange/rouge
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-warning",  # Orange pour la marque
    "accent": "accent-warning",        # Accent orange
    "navbar": "navbar-warning navbar-dark",  # Navbar orange sombre
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-warning",  # Sidebar sombre avec accent orange
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",               # Thème sombre
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-warning",    # Boutons principaux en orange
        "secondary": "btn-outline-secondary",
        "info": "btn-outline-info",
        "warning": "btn-warning",    # Orange vif
        "danger": "btn-danger",      # Rouge pour danger
        "success": "btn-success"
    },
    "actions_sticky_top": False
}


# Firebase Cloud Messaging Configuration
import os
FCM_SERVICE_ACCOUNT_PATH = os.path.join(BASE_DIR, 'api', 'secret', 'woila-4be6b-firebase-adminsdk-fbsvc-14075b647a.json')