# Generated by Django 5.2.4 on 2025-10-03 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_create_vip_zones_tables'),
        ('order', '0001_initial'),
        ('users', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicletype', verbose_name='Type de véhicule'),
        ),
        migrations.AddField(
            model_name='order',
            name='vip_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vipzoneproxy', verbose_name='Zone VIP'),
        ),
        migrations.AddField(
            model_name='driverpool',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_pool', to='order.order'),
        ),
        migrations.AddField(
            model_name='customerstatus',
            name='current_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_tracking', to='order.order', verbose_name='Commande active'),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.usercustomer'),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userdriver'),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='order.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.paymentmethod', verbose_name='Méthode de paiement'),
        ),
        migrations.AddField(
            model_name='rating',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='order.order'),
        ),
        migrations.AddField(
            model_name='rating',
            name='rated_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='users.usercustomer'),
        ),
        migrations.AddField(
            model_name='rating',
            name='rated_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='users.userdriver'),
        ),
        migrations.AddField(
            model_name='rating',
            name='rater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to='users.userdriver'),
        ),
        migrations.AddField(
            model_name='triptracking',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_tracking', to='users.userdriver'),
        ),
        migrations.AddField(
            model_name='triptracking',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_tracking', to='order.order'),
        ),
        migrations.AddIndex(
            model_name='driverstatus',
            index=models.Index(fields=['status'], name='driver_stat_status_9ca853_idx'),
        ),
        migrations.AddIndex(
            model_name='driverstatus',
            index=models.Index(fields=['current_latitude', 'current_longitude'], name='driver_stat_current_3eac3e_idx'),
        ),
        migrations.AddIndex(
            model_name='driverpool',
            index=models.Index(fields=['order', 'priority_order'], name='driver_pool_order_i_86c22f_idx'),
        ),
        migrations.AddIndex(
            model_name='driverpool',
            index=models.Index(fields=['request_status'], name='driver_pool_request_246954_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='driverpool',
            unique_together={('order', 'driver')},
        ),
        migrations.AddIndex(
            model_name='customerstatus',
            index=models.Index(fields=['current_latitude', 'current_longitude'], name='customer_st_current_95680b_idx'),
        ),
        migrations.AddIndex(
            model_name='customerstatus',
            index=models.Index(fields=['current_order'], name='customer_st_current_d366ef_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertracking',
            index=models.Index(fields=['order', '-created_at'], name='order_track_order_i_5a6800_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertracking',
            index=models.Index(fields=['event_type'], name='order_track_event_t_062397_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='orders_created_b25042_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_status_762191_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer'], name='orders_custome_6c3a7f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['driver'], name='orders_driver__f31fef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('order', 'rating_type')},
        ),
        migrations.AddIndex(
            model_name='triptracking',
            index=models.Index(fields=['order', 'recorded_at'], name='trip_tracki_order_i_d1cfe3_idx'),
        ),
        migrations.AddIndex(
            model_name='triptracking',
            index=models.Index(fields=['latitude', 'longitude'], name='trip_tracki_latitud_9e308f_idx'),
        ),
    ]
