# Generated by Django 5.2.6 on 2025-09-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipZoneKilometerRuleProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_kilometers', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prix_jour_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_nuit_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': '📏 Règle kilométrique VIP',
                'verbose_name_plural': '📏 Règles kilométriques VIP',
                'db_table': 'vip_zone_kilometer_rules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VipZoneProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('prix_jour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_nuit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': '👑 Zone VIP',
                'verbose_name_plural': '👑 Zones VIP',
                'db_table': 'vip_zones',
                'managed': False,
            },
        ),
    ]
