# Generated by Django 5.2.6 on 2025-10-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name="Message d'erreur", help_text="Message d'erreur en cas d'échec de la transaction"),
        ),
    ]
