# Generated by Django 5.2.4 on 2025-09-25 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du pays')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': '🌍 Pays',
                'verbose_name_plural': '🌍 Pays',
                'db_table': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeneralConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la configuration')),
                ('search_key', models.CharField(max_length=100, unique=True, verbose_name='Clé de recherche')),
                ('valeur', models.TextField(help_text='Valeur de la configuration (peut être castée en nombre si nécessaire)', verbose_name='Valeur')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Configuration Générale',
                'verbose_name_plural': 'Configurations',
                'db_table': 'general_configs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la ville')),
                ('prix_jour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix jour (FCFA)')),
                ('prix_nuit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix nuit (FCFA)')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='core.country', verbose_name='Pays')),
            ],
            options={
                'verbose_name': '🏙️ Ville',
                'verbose_name_plural': '🏙️ Villes',
                'db_table': 'cities',
                'ordering': ['country__name', 'name'],
                'unique_together': {('country', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VipZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la zone VIP')),
                ('additional_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant additionnel (FCFA)')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_zones', to='core.city', verbose_name='Ville')),
            ],
            options={
                'verbose_name': '⭐ Zone VIP',
                'verbose_name_plural': '⭐ Zones VIP',
                'db_table': 'vip_zones',
                'ordering': ['city__name', 'name'],
                'unique_together': {('city', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VipZoneKilometerRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_km', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Kilomètres minimum')),
                ('max_km', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Kilomètres maximum')),
                ('additional_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant additionnel (FCFA)')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('vip_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kilometer_rules', to='core.vipzone', verbose_name='Zone VIP')),
            ],
            options={
                'verbose_name': '📏 Règle kilométrique VIP',
                'verbose_name_plural': '📏 Règles kilométriques VIP',
                'db_table': 'vip_zone_kilometer_rules',
                'ordering': ['vip_zone__name', 'min_km'],
            },
        ),
    ]
