# Generated by Django 5.2.6 on 2025-10-03 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vipzonekilometerruleproxy_vipzoneproxy'),
    ]

    operations = [
        migrations.RunSQL(
            # Create vip_zones table
            sql="""
                CREATE TABLE IF NOT EXISTS vip_zones (
                    id SERIAL PRIMARY KEY,
                    name VARCHAR(100) UNIQUE NOT NULL,
                    prix_jour DECIMAL(10, 2) NOT NULL,
                    prix_nuit DECIMAL(10, 2) NOT NULL,
                    active BOOLEAN NOT NULL DEFAULT TRUE,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                );
            """,
            reverse_sql="DROP TABLE IF EXISTS vip_zones CASCADE;"
        ),
        migrations.RunSQL(
            # Create vip_zone_kilometer_rules table
            sql="""
                CREATE TABLE IF NOT EXISTS vip_zone_kilometer_rules (
                    id SERIAL PRIMARY KEY,
                    vip_zone_id INTEGER NOT NULL REFERENCES vip_zones(id) ON DELETE CASCADE,
                    min_kilometers DECIMAL(5, 2) NOT NULL,
                    prix_jour_per_km DECIMAL(10, 2) NOT NULL,
                    prix_nuit_per_km DECIMAL(10, 2) NOT NULL,
                    active BOOLEAN NOT NULL DEFAULT TRUE,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                );
            """,
            reverse_sql="DROP TABLE IF EXISTS vip_zone_kilometer_rules CASCADE;"
        ),
    ]
