# Generated by Django 5.2.4 on 2025-09-11 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_wallettransaction'),
        ('order', '0002_driverpool_paymentmethod_rating_triptracking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude actuelle')),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitude actuelle')),
                ('last_location_update', models.DateTimeField(blank=True, null=True, verbose_name='Dernière MAJ position')),
                ('websocket_channel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Canal WebSocket')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('current_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_tracking', to='order.order', verbose_name='Commande active')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='api.usercustomer')),
            ],
            options={
                'verbose_name': 'Statut Client',
                'verbose_name_plural': 'Statuts Clients',
                'db_table': 'customer_status',
                'indexes': [models.Index(fields=['current_latitude', 'current_longitude'], name='customer_st_current_95680b_idx'), models.Index(fields=['current_order'], name='customer_st_current_d366ef_idx')],
            },
        ),
    ]
